### ISSUE TITLE
Resolve your Github Workflow error

### ISSUE THREAD

**Issue by nadirdeveloper** [Sazahiba/class-02#1]
Assalam-o-Alikum,
You are getting the error on build because in your repository. you have two folder one for workflow and another one is class in which your code is located.
So you are getting error on build task because the workflow is trying to find the code in the main directory. but it is located in class folder .
You can resolve it by two ways:
1) you should should add the code from class folder like using git init command inside the class folder
2) in your workflow when you are build change the directory to class using ./class

if it not work ask me again
thanks

**Comment by Sazahiba** [comment]
Thank you so so much. I will follow the instructions given by you.

Thanks
Saba

**Comment by nadirdeveloper** [comment]
Is it is resolved or not?
did you tried it or not?

**Comment by Sazahiba** [comment]
I will try it tonight ☺️

**Comment by Sazahiba** [comment]
> Is it is resolved or not?
> did you tried it or not?

I just tried both..it's not working :(

**Comment by nadirdeveloper** [comment]
there is another error in your surge url.
if you don't mind i can connect to your system and fix error?

**Comment by Sazahiba** [comment]
> there is another error in your surge url.
> if you don't mind i can connect to your system and fix error?

Yes please, I was searching the whole FB for your id to ask for the same.

**Comment by Sazahiba** [comment]
How will you connect it ? through team viewer? or something else?

**Comment by nadirdeveloper** [comment]
ok teamview or anydesk any

**Comment by Sazahiba** [comment]
I have zoom for now. I need to install team viewer. please wait

**Comment by nadirdeveloper** [comment]
might continue conservation at 
https://www.facebook.com/nadirali.abro.58

**Comment by Sazahiba** [comment]
> might continue conservation at
> https://www.facebook.com/nadirali.abro.58

Okay please check your FB
